/*  
 * 	Com base na quantidad de clientes atendidos com danone.
 *	Todos são 50% exceto PRA Levar MORANGO QUE É 70%
 * 	CRIAR PARTE DE CONTROLE DOS ITENS
 * 		1. GERAR LISTA DE CLIENTES ATENDIDOS DADOS.
 * 		2. CONTROLE DO QUE FOI POSITIVADO POR CLIENTE - CONDICIONAL.
 * 		3. VERIFICAR SE NESSE CLIENTE POSITIVADO FOI COM TODOS OS (13) ITENS. 
*/

WITH DN_TOTAL as (   --TOTAL
        SELECT 
            PED.CODUSUR AS RCA,
            COUNT(DISTINCT PED.CODCLI) AS DN
        FROM 
            PONTUAL.PCPEDC PED
            JOIN PONTUAL.PCPEDI PEDI ON PEDI.NUMPED = PED.NUMPED
            JOIN PONTUAL.PCPRODUT PROD ON PEDI.CODPROD = PROD.CODPROD
        WHERE 
            PED.DATA BETWEEN TRUNC(SYSDATE, 'MM') and LAST_DAY(SYSDATE)
            AND PROD.CODFORNEC = 588 -- Danone
            AND PED.CODUSUR = {rca}
            AND PED.DTCANCEL IS NULL
            AND PED.POSICAO IN ('F')
            AND PED.CONDVENDA IN (1, 2, 3, 7, 9, 14, 15, 17, 18, 19, 98)
        GROUP BY 
            PED.CODUSUR)
        
        
SELECT 
	--(SELECT SUBSTR(PCUSUARI.NOME, INSTR(PCUSUARI.NOME, ' ') + 1, INSTR(PCUSUARI.NOME, ' ', INSTR(PCUSUARI.NOME, ' ') + 1) - INSTR(PCUSUARI.NOME, ' ') - 1) FROM PONTUAL.PCUSUARI WHERE PCUSUARI.CODUSUR = DN_TOTAL.RCA) AS NOME,
	NVL(DN_TOTAL.DN, 0) AS REALIZADO
FROM   
	DN_TOTAL 
