WITH DN_TOTAL as (   --TOTAL
        SELECT 
            PED.CODSUPERVISOR AS SUP,
            COUNT(DISTINCT PED.CODCLI) AS DN
        FROM 
            PONTUAL.PCPEDC PED
            JOIN PONTUAL.PCPEDI PEDI ON PEDI.NUMPED = PED.NUMPED
            JOIN PONTUAL.PCPRODUT PROD ON PEDI.CODPROD = PROD.CODPROD
        WHERE 
            PED.DATA BETWEEN TRUNC(SYSDATE, 'MM') and LAST_DAY(SYSDATE)
            AND PROD.CODFORNEC = 588 -- Danone
            AND PED.CODSUPERVISOR = {sup}
            AND PED.DTCANCEL IS NULL
            AND PED.POSICAO IN ('F')
            AND PED.CONDVENDA IN (1, 2, 3, 7, 9, 14, 15, 17, 18, 19, 98)
        GROUP BY 
            PED.CODSUPERVISOR)
        
        
SELECT 
	NVL(DN_TOTAL.DN, 0) AS REALIZADO
FROM   
	DN_TOTAL 
