WITH DN_TOTAL as (
    SELECT 
    	DISTINCT (PED.CODCLI),    
    	PED.CODUSUR AS COD
    FROM 
        PONTUAL.PCPEDC PED
        JOIN PONTUAL.PCPEDI PEDI ON PEDI.NUMPED = PED.NUMPED
        JOIN PONTUAL.PCPRODUT PROD ON PEDI.CODPROD = PROD.CODPROD
    WHERE 
        PED.DATA BETWEEN TRUNC(SYSDATE, 'MM') and LAST_DAY(SYSDATE)
        AND PROD.CODFORNEC = 588 -- Danone
        AND PED.CODUSUR = {rca}
        AND PED.DTCANCEL IS NULL
        AND PED.POSICAO IN ('F')
        AND PED.CONDVENDA IN (1, 2, 3, 7, 9, 14, 15, 17, 18, 19, 98)    
),

CLIENTES AS (
    SELECT
        CLI.CODCLI,
        CLI.CLIENTE,
        CLI.FANTASIA,
        CLI.MUNICCOM
    FROM
        PONTUAL.PCCLIENT CLI
    WHERE
        CLI.CODCLI IN (SELECT CODCLI FROM DN_TOTAL)
)
        
SELECT
	DN_TOTAL.COD,
	(SELECT SUBSTR(PCUSUARI.NOME, INSTR(PCUSUARI.NOME, ' ') + 1, INSTR(PCUSUARI.NOME, ' ', INSTR(PCUSUARI.NOME, ' ') + 1) - INSTR(PCUSUARI.NOME, ' ') - 1) FROM PONTUAL.PCUSUARI WHERE PCUSUARI.CODUSUR = DN_TOTAL.COD) AS NOME
FROM   
	DN_TOTAL 